# Generated by Django 3.0.8 on 2020-07-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortened_Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=16, unique=True)),
                ('origin_url', models.URLField(max_length=2048)),
            ],
        ),
    ]
